/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonnelImport } from './routes/personnel'
import { Route as IndexImport } from './routes/index'
import { Route as PersonnelLayoutImport } from './routes/personnel/_layout'
import { Route as LocomotifGetStartedImport } from './routes/locomotif/get-started'
import { Route as FacilityLayoutImport } from './routes/facility/_layout'
import { Route as LocomotifAuthLayoutImport } from './routes/locomotif/auth/_layout'
import { Route as FacilityLayoutPublishImport } from './routes/facility/_layout.publish'
import { Route as FacilityLayoutOverviewImport } from './routes/facility/_layout.overview'
import { Route as FacilityLayoutMypostingsImport } from './routes/facility/_layout.mypostings'
import { Route as LocomotifAuthLayoutPersonnelSignUpImport } from './routes/locomotif/auth/_layout.personnel-sign-up'
import { Route as LocomotifAuthLayoutFacilitySignUpImport } from './routes/locomotif/auth/_layout.facility-sign-up'

// Create Virtual Routes

const FacilityImport = createFileRoute('/facility')()
const LocomotifAuthImport = createFileRoute('/locomotif/auth')()

// Create/Update Routes

const FacilityRoute = FacilityImport.update({
  path: '/facility',
  getParentRoute: () => rootRoute,
} as any)

const PersonnelRoute = PersonnelImport.update({
  path: '/personnel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocomotifAuthRoute = LocomotifAuthImport.update({
  path: '/locomotif/auth',
  getParentRoute: () => rootRoute,
} as any)

const PersonnelLayoutRoute = PersonnelLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => PersonnelRoute,
} as any)

const LocomotifGetStartedRoute = LocomotifGetStartedImport.update({
  path: '/locomotif/get-started',
  getParentRoute: () => rootRoute,
} as any)

const FacilityLayoutRoute = FacilityLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => FacilityRoute,
} as any)

const LocomotifAuthLayoutRoute = LocomotifAuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LocomotifAuthRoute,
} as any)

const FacilityLayoutPublishRoute = FacilityLayoutPublishImport.update({
  path: '/publish',
  getParentRoute: () => FacilityLayoutRoute,
} as any)

const FacilityLayoutOverviewRoute = FacilityLayoutOverviewImport.update({
  path: '/overview',
  getParentRoute: () => FacilityLayoutRoute,
} as any)

const FacilityLayoutMypostingsRoute = FacilityLayoutMypostingsImport.update({
  path: '/mypostings',
  getParentRoute: () => FacilityLayoutRoute,
} as any)

const LocomotifAuthLayoutPersonnelSignUpRoute =
  LocomotifAuthLayoutPersonnelSignUpImport.update({
    path: '/personnel-sign-up',
    getParentRoute: () => LocomotifAuthLayoutRoute,
  } as any)

const LocomotifAuthLayoutFacilitySignUpRoute =
  LocomotifAuthLayoutFacilitySignUpImport.update({
    path: '/facility-sign-up',
    getParentRoute: () => LocomotifAuthLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelImport
      parentRoute: typeof rootRoute
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityImport
      parentRoute: typeof rootRoute
    }
    '/facility/_layout': {
      id: '/facility/_layout'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityLayoutImport
      parentRoute: typeof FacilityRoute
    }
    '/locomotif/get-started': {
      id: '/locomotif/get-started'
      path: '/locomotif/get-started'
      fullPath: '/locomotif/get-started'
      preLoaderRoute: typeof LocomotifGetStartedImport
      parentRoute: typeof rootRoute
    }
    '/personnel/_layout': {
      id: '/personnel/_layout'
      path: ''
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelLayoutImport
      parentRoute: typeof PersonnelImport
    }
    '/facility/_layout/mypostings': {
      id: '/facility/_layout/mypostings'
      path: '/mypostings'
      fullPath: '/facility/mypostings'
      preLoaderRoute: typeof FacilityLayoutMypostingsImport
      parentRoute: typeof FacilityLayoutImport
    }
    '/facility/_layout/overview': {
      id: '/facility/_layout/overview'
      path: '/overview'
      fullPath: '/facility/overview'
      preLoaderRoute: typeof FacilityLayoutOverviewImport
      parentRoute: typeof FacilityLayoutImport
    }
    '/facility/_layout/publish': {
      id: '/facility/_layout/publish'
      path: '/publish'
      fullPath: '/facility/publish'
      preLoaderRoute: typeof FacilityLayoutPublishImport
      parentRoute: typeof FacilityLayoutImport
    }
    '/locomotif/auth': {
      id: '/locomotif/auth'
      path: '/locomotif/auth'
      fullPath: '/locomotif/auth'
      preLoaderRoute: typeof LocomotifAuthImport
      parentRoute: typeof rootRoute
    }
    '/locomotif/auth/_layout': {
      id: '/locomotif/auth/_layout'
      path: '/locomotif/auth'
      fullPath: '/locomotif/auth'
      preLoaderRoute: typeof LocomotifAuthLayoutImport
      parentRoute: typeof LocomotifAuthRoute
    }
    '/locomotif/auth/_layout/facility-sign-up': {
      id: '/locomotif/auth/_layout/facility-sign-up'
      path: '/facility-sign-up'
      fullPath: '/locomotif/auth/facility-sign-up'
      preLoaderRoute: typeof LocomotifAuthLayoutFacilitySignUpImport
      parentRoute: typeof LocomotifAuthLayoutImport
    }
    '/locomotif/auth/_layout/personnel-sign-up': {
      id: '/locomotif/auth/_layout/personnel-sign-up'
      path: '/personnel-sign-up'
      fullPath: '/locomotif/auth/personnel-sign-up'
      preLoaderRoute: typeof LocomotifAuthLayoutPersonnelSignUpImport
      parentRoute: typeof LocomotifAuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PersonnelRoute: PersonnelRoute.addChildren({}),
  FacilityRoute: FacilityRoute.addChildren({
    FacilityLayoutRoute: FacilityLayoutRoute.addChildren({
      FacilityLayoutMypostingsRoute,
      FacilityLayoutOverviewRoute,
      FacilityLayoutPublishRoute,
    }),
  }),
  LocomotifGetStartedRoute,
  LocomotifAuthRoute: LocomotifAuthRoute.addChildren({
    LocomotifAuthLayoutRoute: LocomotifAuthLayoutRoute.addChildren({
      LocomotifAuthLayoutFacilitySignUpRoute,
      LocomotifAuthLayoutPersonnelSignUpRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/personnel",
        "/facility",
        "/locomotif/get-started",
        "/locomotif/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/personnel": {
      "filePath": "personnel.tsx",
      "children": [
        "/personnel/_layout"
      ]
    },
    "/facility": {
      "filePath": "facility",
      "children": [
        "/facility/_layout"
      ]
    },
    "/facility/_layout": {
      "filePath": "facility/_layout.tsx",
      "parent": "/facility",
      "children": [
        "/facility/_layout/mypostings",
        "/facility/_layout/overview",
        "/facility/_layout/publish"
      ]
    },
    "/locomotif/get-started": {
      "filePath": "locomotif/get-started.tsx"
    },
    "/personnel/_layout": {
      "filePath": "personnel/_layout.tsx",
      "parent": "/personnel"
    },
    "/facility/_layout/mypostings": {
      "filePath": "facility/_layout.mypostings.tsx",
      "parent": "/facility/_layout"
    },
    "/facility/_layout/overview": {
      "filePath": "facility/_layout.overview.tsx",
      "parent": "/facility/_layout"
    },
    "/facility/_layout/publish": {
      "filePath": "facility/_layout.publish.tsx",
      "parent": "/facility/_layout"
    },
    "/locomotif/auth": {
      "filePath": "locomotif/auth",
      "children": [
        "/locomotif/auth/_layout"
      ]
    },
    "/locomotif/auth/_layout": {
      "filePath": "locomotif/auth/_layout.tsx",
      "parent": "/locomotif/auth",
      "children": [
        "/locomotif/auth/_layout/facility-sign-up",
        "/locomotif/auth/_layout/personnel-sign-up"
      ]
    },
    "/locomotif/auth/_layout/facility-sign-up": {
      "filePath": "locomotif/auth/_layout.facility-sign-up.tsx",
      "parent": "/locomotif/auth/_layout"
    },
    "/locomotif/auth/_layout/personnel-sign-up": {
      "filePath": "locomotif/auth/_layout.personnel-sign-up.tsx",
      "parent": "/locomotif/auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
